### ISSUE TITLE
view

### ISSUE THREAD

**Issue by hanjo8813** [hanjo8813/Programmers_Devcourse_Lab#2]
![header](https://capsule-render.vercel.app/api?type=waving&color=0f7b6c&height=150&section=header&text=hanjo&fontColor=afeee6&fontSize=90&animation=twinkling)

<div align='center'>
    <h2> Today I Learned </h2>
</div>

<br>

> 백엔드 - 1기 - C - 한재원

## 4주차 TIL

|날짜|제목|링크|
|---|---|---|
|`W4D1`|소프트웨어 테스팅|https://hanjo8813.github.io/til/17/|
|`W4D2`|Docker-MySQL, JDBC 기초|https://hanjo8813.github.io/til/18/|
|`W4D3`|Data Source, JDBC Template|https://hanjo8813.github.io/til/19/|
|`W4D4`|Embedded DB, NamedParmeter JDBC Template|https://hanjo8813.github.io/til/20/|
|`W4D5`|Spring AOP, Transaction|https://hanjo8813.github.io/til/21/<br>https://hanjo8813.github.io/til/22/|

<br>

## 3주차 TIL

|날짜|제목|링크|
|---|---|---|
|`W3D1`|Spring 기초|https://hanjo8813.github.io/til/12/|
|`W3D2`|IoC, DDD, DI|https://hanjo8813.github.io/til/13/|
|`W3D3`|ComponentScan, Auto Wired, Bean Scope|https://hanjo8813.github.io/til/14/|
|`W3D4`|Resuource 요소|https://hanjo8813.github.io/til/15/|
|`W3D5`|Logging 처리하기|https://hanjo8813.github.io/til/16/|

<br>

## 2주차 TIL

|날짜|제목|링크|
|---|---|---|
|`W2D1`|데이터베이스 기초|[블로그](https://hanjo8813.github.io/til/7/)|
|`W2D2`|MySQL, Docekr 사용법|[블로그](https://hanjo8813.github.io/til/8/)|
|`W2D3`|SELECT, GROUP BY|[블로그](https://hanjo8813.github.io/til/9/)|
|`W2D4`|Insert, Update, Join|[블로그](https://hanjo8813.github.io/til/10/)|
|`W2D5`|MySQL 고급기능 사용하기|[블로그](https://hanjo8813.github.io/til/11/)|

<br>

## 1주차 TIL

|날짜|제목|링크|
|---|---|---|
|`W1D1`|Java 기초 및 개발환경 세팅|[블로그](https://hanjo8813.github.io/til/1/)|
|`W1D2`|객체지향 프로그래밍(OOP)|[블로그](https://hanjo8813.github.io/til/2/)|
|`W1D2`|Git 야무지게 사용하기|[블로그](https://hanjo8813.github.io/til/3/)|
|`W1D3`|Interface 이야기|[블로그](https://hanjo8813.github.io/til/4/)|
|`W1D4`|Collection 이야기|[블로그](https://hanjo8813.github.io/til/5/)|
|`W1D5`|Gradle로 프로젝트 만들기|[블로그](https://hanjo8813.github.io/til/6/)|

**Comment by hanjo8813** [comment]
## 개념 복습

- DI 의존성주입 
- IoC 컨테이너 정리
- Profile

### Component vs Bean
- `@Component`
   - target: class, interface
- `@Bean`
   - target: method
   - 개발자가 컨트롤이 불가능한 외부 라이브러리들을 Bean으로 등록하고 싶은 경우

### Auto Wired 다시보기

- Component를 Bean으로 만들겠다고 약속하는 것 
- 단위테스트시엔 AutoWired를 쓰지않고 생성자 주입 방식을 사용함 -> mock을 사용한 테스트 용이
- 의존성주입시 생성자 사용이 가장 좋은 이유? 

<br>

###  Bean Scope에 대해

- Bean을 프로토타입으로 사용할 땐 어떻게 할까?
- 스프링 컨테이너는 Bean 생성 주입 초기화까지만 처리하므로 싱글톤을 쓰는게 좋다!
- 만약 아니라면 직접 생명주기를 관리해줘야함.
- 이렇게 번거로운데도 프로토타입을 쓸 일이 있을까? (멘토님께 자문을..!)
   - 거의 사용하는 일은 없다. 실시간으로 상태가 변할때 사용할수도 있다.
   - Spring의 장점은 Bean의 생명주기 관리에 있기 때문!

<br>

### DTO vs VO

- 애초에 비슷한 친구들이다. 이름 그 자체에서 뜻을 읽자
- Value Object : **값 자체**로써의 목표가 있는 객체
- Data Transfer Object : **값 전달**의 목적이 있는 객체
- 쉽게 이해하자면? -> DTO는 쇼핑카트이고 VO는 라면이다! (Tyler 曰)

<br>

### Return Type에 대하여

- (강의내용 중) 메소드의 리턴값이 void여도 되는 상황일 때 굳이 왜 변경값까지 리턴할까?
- 변경된 값을 연속적으로 사용해야할 경우가 있을 수 있음

<br>

### POJO(Plain Old Java Object)란?

- Spring은 POJO 기반 프레임워크다! -> 뭔소리냐? -> 구식이다
   - Java언어 외 제약없음
   - 특정환경에 종속 X
   - 객체지향적이다
- 간결한 코드 + 테스트가 용이하다.
- 지금 우리가 사용하는 스프링이 모두 POJO

<br>

### 화상 코드리뷰

- 멘토님 주관하에 Zoom 화상회의를 통해 공개 코드리뷰를 진행하였습니다.
- reviewee 3명을 선정하여 각자 과제 코드를 설명하고, 나머지는 reviewer가 되어 코드리뷰를 합니다.
- 설명이 끝나면 reviewer는 코드에 대해 궁금한점과 피드백을 주는 방식으로 진행하였습니다
- 집단지성을 활용해 코드 퀄리티를 높힐 수 있는 좋은 시간이였습니다

**Comment by Jummi10** [comment]
### Component vs Bean
- `@Component`
   - target: class, interface
- `@Bean`
   - target: method
   - 개발자가 컨트롤이 불가능한 외부 라이브러리들을 Bean으로 등록하고 싶은 경우
 
이 정도면 될 것 같아요!

**Comment by hanjo8813** [comment]
인텔리제이 단축키

|단축키|설명|
|---|---|
|`psvm`|public static void main|
|`sout`|System.out.println|
|`Alt + Enter`|수정 도우미|
|`Ctrl + Space`|추천 도우미|
|`Ctrl + Alt + L`|코드 정렬|
|`Ctrl + Shift + Alt + T`|리팩토링 메뉴(중요)|
|`Ctrl + Alt + V`|변수 리팩토링|
|`Alt + I` (원래 insert)|오버라이딩 단축키(난 i로 바꿈)|

**Comment by hanjo8813** [comment]
# 코딩 테스트 대비

### Python + Java 둘다 써서 코테 풀이~

<br>
